-- =====================================================================
-- Datos semilla: zonas, agencias/joyerías, jefes zonales y catálogo POP
-- real de Orocash. Generado a partir de 'agencias y zonales.xlsx'.
-- Los USUARIOS (admin + 10 jefes zonales) se crean con scripts/seed-users.ts
-- porque requieren el API de Supabase Auth (no se pueden insertar por SQL
-- plano con contraseña en texto).
-- =====================================================================

insert into public.zones (name, description) values
  ('ESMERALDAS', 'Jefatura zonal a cargo de Ivan Dario'),
  ('ZONA CENTRO', 'Jefatura zonal a cargo de Pablo Hernandez'),
  ('PORTOVIEJO', 'Jefatura zonal a cargo de Efren Londoño'),
  ('QUITO NORTE', 'Jefatura zonal a cargo de Jorge Higuita'),
  ('ZONA CENTRO NORTE', 'Jefatura zonal a cargo de Alfredo Segura'),
  ('AMBATO', 'Jefatura zonal a cargo de Wilmar Sanchez'),
  ('MACHALA', 'Jefatura zonal a cargo de Atilio Manzano'),
  ('ZONA NORTE', 'Jefatura zonal a cargo de Harold Bedoya'),
  ('ZONA SUR', 'Jefatura zonal a cargo de Oswaldo Rincon'),
  ('QUITO SUR', 'Jefatura zonal a cargo de Jefferson Luna');

-- Agencias / joyerías reales (101), vinculadas a su zona por nombre.
insert into public.stores (code, name, city, province, zone_id, email, phone, company, status) values
  ('E-208', 'OROCASH ECUADOR', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e208@orocash.ec', '096-886-7435', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-204', 'OROCASH LA MONEDA ESMERALDA', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e204@orocash.ec', '096-864-6872', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-205', 'OROCASH LA SOLUCIÓN', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e205@orocash.ec', '096-891-8316', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-201', 'OROCASH LAS PALMAS', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e201@orocash.ec', '099-829-8367', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-202', 'OROCASH OLMEDO', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e202@orocash.ec', '096-995-3931', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-210', 'OROCASH COSTEÑITA', 'San Lorenzo', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e210@orocash.ec', '096-885-0155', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-212', 'OROCASH SAN LORENZO', 'San Lorenzo', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e212@orocash.ec', '096-900-7371', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-211', 'OROCASH CODESA', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e211@orocash.ec', '098-152-3548', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-209', 'OROCASH LA TOLITA', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e209@orocash.ec', 'o99 105 2078', 'AURUM-ECUADOR AUREC S.A.', 'active'),
  ('E-01', 'OROCASH GUAYAQUIL', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e01@orocash.ec', '099-998-6373', 'COMMERCORPLUS S.A', 'active'),
  ('E-26', 'OROCASH JIPIJAPA', 'Jipijapa', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e26@orocash.ec', '099-895-3507', 'COMMERCORPLUS S.A', 'active'),
  ('E-10', 'OROCASH BABAHOYO', 'Babahoyo', 'Los Ríos', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e10@orocash.ec', '098-710-8705', 'METALTEXCORP S.A', 'active'),
  ('E-03', 'OROCASH DINERO YA', 'Babahoyo', 'Los Ríos', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e03@orocash.ec', '099-863-0372', 'METALTEXCORP S.A', 'active'),
  ('E-33', 'OROCASH EL CONDADO', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e33@orocash.ec', '098-355-7778', 'COMMERCORPLUS S.A', 'active'),
  ('E-30', 'OROCASH LA 27', 'Babahoyo', 'Los Ríos', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e30@orocash.ec', '099-515-0033', 'METALTEXCORP S.A', 'active'),
  ('E-36', 'OROCASH 9 DE OCTUBRE', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e36@orocash.ec', '098-015-9027', 'METALTEXCORP S.A', 'active'),
  ('E-39', 'OROCASH BOYACA', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e39@orocash.ec', '098-436-6550', 'METALTEXCORP S.A', 'active'),
  ('E-06', 'OROCASH COSTA DE ORO', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e06@orocash.ec', '099-295-0796', 'METALTEXCORP S.A', 'active'),
  ('E-08', 'OROCASH LA FAVORITA', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e08@orocash.ec', '098-497-5257', 'METALTEXCORP S.A', 'active'),
  ('E-04', 'OROCASH SOL DE ORO', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e04@orocash.ec', '099-298-0264', 'METALTEXCORP S.A', 'active'),
  ('E-53', 'OROCASH CENTRO FINANCIERO', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e53@orocash.ec', '099-329-5232', 'COMMERCORPLUS S.A', 'active'),
  ('E-19', 'OROCASH VENTANAS', 'Ventanas', 'Los Ríos', (select id from public.zones where name = 'ZONA CENTRO'), 'joyeria-e19@orocash.ec', '098-488-1804', 'METALTEXCORP S.A', 'active'),
  ('E-15', 'OROCASH EL EMPALME', 'El Empalme', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e15@orocash.ec', '098-488-8089', 'COMMERCORPLUS S.A', 'active'),
  ('E-172', 'OROCASH CALCETA', 'Calceta', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e172@orocash.ec', '099-002-7711', 'METALSUD S.A', 'active'),
  ('E-159', 'OROCASH CHONE', 'Chone', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e159@orocash.ec', '096-737-0491', 'METALSUD S.A', 'active'),
  ('E-171', 'OROCASH WASHINGTON 2', 'Chone', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e171@orocash.ec', '098-095-7136', 'METALSUD S.A', 'active'),
  ('E-23', 'OROCASH SAN MARÍN', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e23@orocash.ec', '099-994-2885', 'COMMERCORPLUS S.A', 'active'),
  ('E-60', 'OROCASH EL COCA', 'El Coca', 'Orellana', (select id from public.zones where name = 'AMBATO'), 'joyeria-e60@orocash.ec', '096-974-3688', 'METALSUD S.A', 'active'),
  ('E-200', 'OROCASH BOLIVAR', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e200@orocash.ec', '099-081-9610', 'METALSUD S.A', 'active'),
  ('E-207', 'OROCASH DON BILLETE', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e207@orocash.ec', '096 935 9682', 'METALSUD S.A', 'active'),
  ('E-203', 'OROCASH LA MEJOR', 'Esmeraldas', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e203@orocash.ec', '096-856-5510', 'METALSUD S.A', 'active'),
  ('E-114', 'OROCASH HUAQUILLAS', 'Huaquillas', 'El Oro', (select id from public.zones where name = 'MACHALA'), 'joyeria-e114@orocash.ec', '099-828-5510', 'METALSUD S.A', 'active'),
  ('E-57', 'OROCASH FARAÓN', 'Lago Agrio', 'Sucumbíos', (select id from public.zones where name = 'AMBATO'), 'joyeria-e57@orocash.ec', '097-943-9596', 'METALSUD S.A', 'active'),
  ('E-64', 'OROCASH LAGO AGRIO', 'Lago Agrio', 'Sucumbíos', (select id from public.zones where name = 'AMBATO'), 'joyeria-e64@orocash.ec', '096-980-6329', 'METALSUD S.A', 'active'),
  ('E-168', 'OROCASH 1 DE ENERO', 'Portoviejo', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e168@orocash.ec', '096-736-9231', 'METALSUD S.A', 'active'),
  ('E-162', 'OROCASH DOLLAR PORTOVIEJO', 'Portoviejo', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e162@orocash.ec', '096-923-0303', 'METALSUD S.A', 'active'),
  ('E-160', 'OROCASH LA PORTOVIEJO', 'Portoviejo', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e160@orocash.ec', '096-737-0484', 'METALSUD S.A', 'active'),
  ('E-161', 'OROCASH MANABITA', 'Portoviejo', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e161@orocash.ec', '097-990-6568', 'METALSUD S.A', 'active'),
  ('E-206', 'OROCASH QUININDÉ', 'Quinindé', 'Esmeraldas', (select id from public.zones where name = 'ESMERALDAS'), 'joyeria-e206@orocash.ec', '096-823-5745', 'METALSUD S.A', 'active'),
  ('E-69', 'OROCASH SHUSHUFINDI', 'Shushufindi', 'Sucumbíos', (select id from public.zones where name = 'AMBATO'), 'joyeria-e69@orocash.ec', '099-175-8435', 'METALSUD S.A', 'active'),
  ('E-24', 'OROCASH URDESA', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e24@orocash.ec', '099-291-2433', 'COMMERCORPLUS S.A', 'active'),
  ('E-12', 'OROCASH DAULE', 'Daule', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e12@orocash.ec', '099-975-3173', 'METALSUD S.A', 'active'),
  ('E-13', 'OROCASH VINCES', 'Vinces', 'Los Ríos', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e13@orocash.ec', '098-488-1803', 'METALSUD S.A', 'active'),
  ('E-51', 'OROCASH LA PROVINCIA', 'Ibarra', 'Imbabura', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e51@orocash.ec', '098-063-5541', 'METALSUD S.A', 'active'),
  ('E-61', 'OROCASH AEROPUERTO', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e61@orocash.ec', '096-700-6310', 'METALSUD S.A', 'active'),
  ('E-05', 'OROCASH EL DOLAR', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e05@orocash.ec', '098-721-9706', 'METALSUD S.A', 'active'),
  ('E-28', 'OROCASH EL REGISTRO', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e28@orocash.ec', '098-481-2524', 'METALSUD S.A', 'active'),
  ('E-29', 'OROCASH PLAZA TRIANGULO', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e29@orocash.ec', '096-922-5617', 'METALTEXCORP S.A', 'active'),
  ('E-166', 'OROCASH REALES TAMARINDOS', 'Portoviejo', 'Manabí', (select id from public.zones where name = 'PORTOVIEJO'), 'joyeria-e166@orocash.ec', '098-462-3900', 'METALSUD S.A', 'active'),
  ('E-34', 'OROCASH ALBOCENTRO', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e34@orocash.ec', '098-436-3512', 'METALTEXCORP S.A', 'active'),
  ('E-48', 'OROCASH LA ROTONDA', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA CENTRO NORTE'), 'joyeria-e48@orocash.ec', '095-890-7548', 'METALTEXCORP S.A', 'active'),
  ('E-25', 'OROCASH LA FE', 'Milagro', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e25@orocash.ec', '099-597-3988', 'COMMERCORPLUS S.A', 'active'),
  ('E-02', 'OROCASH MILAGRO', 'Milagro', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e02@orocash.ec', '099-978-1669', 'COMMERCORPLUS S.A', 'active'),
  ('E-21', 'OROCASH AURORA', 'Daule', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e21@orocash.ec', '096-948-6968', 'COMMERCORPLUS S.A', 'active'),
  ('E-22', 'OROCASH INSTANTANEA', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e22@orocash.ec', '098-481-2930', 'COMMERCORPLUS S.A', 'active'),
  ('E-32', 'OROCASH LA 9', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e32@orocash.ec', '099-295-0603', 'COMMERCORPLUS S.A', 'active'),
  ('E-09', 'OROCASH ENTRE RÍOS', 'Samborondo', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e09@orocash.ec', '098-976-1703', 'COMMERCORPLUS S.A', 'active'),
  ('E-14', 'OROCASH LA OFERTA', 'Troncal', 'Cañar', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e14@orocash.ec', '099-554-3501', 'METALTEXCORP S.A', 'active'),
  ('E-50', 'OROCASH DURÁN', 'Durán', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e50@orocash.ec', '098-405-5020', 'METALTEXCORP S.A', 'active'),
  ('E-44', 'OROCASH BASTION (PLAZA TÍA)', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e44@orocash.ec', '095-882-9901', 'METALTEXCORP S.A', 'active'),
  ('E-46', 'OROCASH OASIS', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA NORTE'), 'joyeria-e46@orocash.ec', '099-845-3449', 'METALTEXCORP S.A', 'active'),
  ('E-27', 'OROCASH LA FLORESTA', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e27@orocash.ec', '098-488-8773', 'COMMERCORPLUS S.A', 'active'),
  ('E-11', 'OROCASH DEL SUR', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e11@orocash.ec', '099-536-1191', 'METALSUD S.A', 'active'),
  ('E-16', 'OROCASH LA 17', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e16@orocash.ec', '098-481-2367', 'METALSUD S.A', 'active'),
  ('E-38', 'OROCASH LA 38', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e38@orocash.ec', '098-724-1083', 'METALSUD S.A', 'active'),
  ('E-18', 'OROCASH LA LIBERTAD', 'La Libertad', 'Santa Elena', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e18@orocash.ec', '099-175-9591', 'METALTEXCORP S.A', 'active'),
  ('E-49', 'OROCASH BLUE COAST', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e49@orocash.ec', '099-119-1505', 'METALTEXCORP S.A', 'active'),
  ('E-35', 'OROCASH ORO SUR', 'Guayaquil', 'Guayas', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e35@orocash.ec', '098-723-9192', 'METALTEXCORP S.A', 'active'),
  ('E-71', 'OROCASH SANGOLQUI', 'Sangolquí', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e71@orocash.ec', '099-995-7570', 'SOCMETASA', 'active'),
  ('E-62', 'OROCASH CUMBAYÁ', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e62@orocash.ec', '098-593-1522', 'SOCMETASA', 'active'),
  ('E-66', 'OROCASH AMAZONAS', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e66@orocash.ec', '099-257-5981', 'SOCMETASA', 'active'),
  ('E-54', 'OROCASH LA ALAMEDA', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e54@orocash.ec', '098-463-0678', 'SOCMETASA', 'active'),
  ('E-63', 'OROCASH LA CENTRAL', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e63@orocash.ec', '098-487-8789', 'SOCMETASA', 'active'),
  ('E-67', 'OROCASH MARIANA DE JESÚS (Prensa)', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e67@orocash.ec', '099-910-4357', 'SOCMETASA', 'active'),
  ('E-52', 'OROCASH QUITO', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e52@orocash.ec', '099-929-7916', 'SOCMETASA', 'active'),
  ('E-70', 'OROCASH SAN RAFAEL', 'Sangolquí', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e70@orocash.ec', '093-989-7968', 'SOCMETASA', 'active'),
  ('E-65', 'OROCASH TULCÁN', 'Tulcán', 'Carchi', (select id from public.zones where name = 'QUITO NORTE'), 'joyeria-e65@orocash.ec', '095-986-9793', 'SOCMETASA', 'active'),
  ('E-56', 'OROCASH ATAHUALPA', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e56@orocash.ec', '099-882-5679', 'SOCMETASA', 'active'),
  ('E-58', 'OROCASH EL PINTADO', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e58@orocash.ec', '099-833-2611', 'SOCMETASA', 'active'),
  ('E-68', 'OROCASH EL RECREO', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e68@orocash.ec', '098-790-5553', 'SOCMETASA', 'active'),
  ('E-55', 'OROCASH LA CAPITAL', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e55@orocash.ec', '098-738-1486', 'SOCMETASA', 'active'),
  ('E-59', 'OROCASH LA MARISCAL', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e59@orocash.ec', '099-500-2768', 'SOCMETASA', 'active'),
  ('E-72', 'OROCASH SOLANDA # 1', 'Quito', 'Pichincha', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e72@orocash.ec', '099-277-6477', 'SOCMETASA', 'active'),
  ('E-101', 'OROCASH AMBATO', 'Ambato', 'Tungurahua', (select id from public.zones where name = 'AMBATO'), 'joyeria-e101@orocash.ec', '099-510-9193', 'UNICASH S.A', 'active'),
  ('E-102', 'OROCASH LA MONARCA', 'Ambato', 'Tungurahua', (select id from public.zones where name = 'AMBATO'), 'joyeria-e102@orocash.ec', '099-291-2779', 'UNICASH S.A', 'active'),
  ('E-108', 'OROCASH TEATRO LALAMA', 'Ambato', 'Tungurahua', (select id from public.zones where name = 'AMBATO'), 'joyeria-e108@orocash.ec', '099-409-0456', 'UNICASH S.A', 'active'),
  ('E-110', 'OROCASH CUENCA', 'Cuenca', 'Azuay', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e110@orocash.ec', '099-295-1279', 'UNICASH S.A', 'active'),
  ('E-109', 'OROCASH LA PERLA', 'Cuenca', 'Azuay', (select id from public.zones where name = 'ZONA SUR'), 'joyeria-e109@orocash.ec', '099-849-4582', 'UNICASH S.A', 'active'),
  ('E-120', 'OROCASH CATAMAYO', 'Loja', 'Loja', (select id from public.zones where name = 'MACHALA'), 'joyeria-e120@orocash.ec', '096-878-2265', 'UNICASH S.A', 'active'),
  ('E-112', 'OROCASH LA MONEDA LOJA', 'Loja', 'Loja', (select id from public.zones where name = 'MACHALA'), 'joyeria-e112@orocash.ec', '098-436-6594', 'UNICASH S.A', 'active'),
  ('E-111', 'OROCASH LOJA', 'Loja', 'Loja', (select id from public.zones where name = 'MACHALA'), 'joyeria-e111@orocash.ec', '098-723-2331', 'UNICASH S.A', 'active'),
  ('E-119', 'OROCASH MACHALA', 'Machala', 'El Oro', (select id from public.zones where name = 'MACHALA'), 'joyeria-e119@orocash.ec', '099-846-5509', 'UNICASH S.A', 'active'),
  ('E-117', 'OROCASH MI TÍO', 'Machala', 'El Oro', (select id from public.zones where name = 'MACHALA'), 'joyeria-e117@orocash.ec', '099-905-6886', 'UNICASH S.A', 'active'),
  ('E-121', 'OROCASH SUPER EFECTIVA', 'Machala', 'El Oro', (select id from public.zones where name = 'MACHALA'), 'joyeria-e121@orocash.ec', '099-843-7639', 'UNICASH S.A', 'active'),
  ('E-113', 'OROCASH NARANJAL', 'Naranjal', 'Guayas', (select id from public.zones where name = 'MACHALA'), 'joyeria-e113@orocash.ec', '099-847-0850', 'UNICASH S.A', 'active'),
  ('E-115', 'OROCASH EL ORO', 'Pasaje', 'El Oro', (select id from public.zones where name = 'MACHALA'), 'joyeria-e115@orocash.ec', '098-723-2327', 'UNICASH S.A', 'active'),
  ('E-107', 'OROCASH CACIQUE', 'Puyo', 'Pastaza', (select id from public.zones where name = 'AMBATO'), 'joyeria-e107@orocash.ec', '099-291-2872', 'UNICASH S.A', 'active'),
  ('E-104', 'OROCASH RIOBAMBA', 'Riobamba', 'Chimborazo', (select id from public.zones where name = 'AMBATO'), 'joyeria-e104@orocash.ec', '099-513-0803', 'UNICASH S.A', 'active'),
  ('E-116', 'OROCASH LA FORTUNA', 'Santa Rosa', 'El Oro', (select id from public.zones where name = 'MACHALA'), 'joyeria-e116@orocash.ec', '099 829 9629', 'UNICASH S.A', 'active'),
  ('E-106', 'OROCASH TENA', 'Tena', 'Napo', (select id from public.zones where name = 'AMBATO'), 'joyeria-e106@orocash.ec', '099-291-2532', 'UNICASH S.A', 'active'),
  ('E-100', 'OROCASH LATACUNGA', 'Latacunga', 'Cotopaxi', (select id from public.zones where name = 'QUITO SUR'), 'joyeria-e100@orocash.ec', '096-278-9386', 'UNICASH S.A', 'active');

-- Catálogo de materiales POP reales de Orocash
insert into public.pop_categories (name) values
  ('Volantes'),
  ('Dípticos'),
  ('Sobres'),
  ('Tarjetas'),
  ('Certificados'),
  ('Institucional'),
  ('Acrílicos y Habladores'),
  ('Rompetráficos')
on conflict (name) do nothing;

insert into public.pop_items (name, category_id, internal_code, total_quantity, warehouse_quantity, low_stock_threshold)
select v.name, c.id, v.code, v.qty, v.qty, v.threshold
from (values
  ('VOLANTES de Compra', 'Volantes', 'VOL-001', 500, 20),
  ('VOLANTES de Venta', 'Volantes', 'VOL-002', 500, 20),
  ('VOLANTES de Graduación', 'Volantes', 'VOL-003', 300, 15),
  ('DÍPTICO joyas de inversión', 'Dípticos', 'DIP-001', 300, 15),
  ('SOBRES para contratos', 'Sobres', 'SOB-001', 1000, 50),
  ('TARJETAS de presentación', 'Tarjetas', 'TAR-001', 2000, 100),
  ('CERTIFICADOS de lingotes', 'Certificados', 'CERT-001', 500, 25),
  ('MISIÓN, VISIÓN Y VALORES', 'Institucional', 'INST-001', 110, 10),
  ('ACRÍLICO / hablador elevado', 'Acrílicos y Habladores', 'ACR-001', 110, 10),
  ('HABLADORES 20X20', 'Acrílicos y Habladores', 'HAB-001', 220, 20),
  ('ROMPETRÁFICO de PISO (estructura)', 'Rompetráficos', 'RT-000', 110, 10),
  ('ROMPETRÁFICO PUBLICIDAD de Grado', 'Rompetráficos', 'RT-001', 110, 10),
  ('ROMPETRÁFICO PUBLICIDAD de Compra', 'Rompetráficos', 'RT-002', 110, 10),
  ('ROMPETRÁFICO PUBLICIDAD de Venta', 'Rompetráficos', 'RT-003', 110, 10),
  ('ROMPETRÁFICO PUBLICIDAD de Relojería', 'Rompetráficos', 'RT-004', 110, 10),
  ('ROMPETRÁFICO PUBLICIDAD de Lingotes', 'Rompetráficos', 'RT-005', 110, 10)
) as v(name, category_name, code, qty, threshold)
join public.pop_categories c on c.name = v.category_name;
