-- =====================================================================
-- Distribución real de material POP instalado por agencia
-- Generado a partir de la hoja 'material pop por agencia' del Excel.
-- Incluye 2 materiales nuevos (LETRERO, PINTURA) no contemplados antes,
-- y el estado real (bueno / desgastado / dañado) de cada instalación.
-- =====================================================================

insert into public.pop_categories (name) values
  ('Letreros'),
  ('Pintura de Fachada')
on conflict (name) do nothing;

insert into public.pop_items (name, category_id, internal_code, total_quantity, warehouse_quantity, assigned_quantity, low_stock_threshold)
select v.name, c.id, v.code, v.total, v.warehouse, v.assigned, 10
from (values
  ('LETRERO institucional', 'Letreros', 'LET-001', 111, 10, 101),
  ('PINTURA de fachada', 'Pintura de Fachada', 'PIN-001', 111, 10, 101)
) as v(name, category_name, code, total, warehouse, assigned)
join public.pop_categories c on c.name = v.category_name;

-- Ajusta cantidades reales de materiales ya existentes según instalación por agencia
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'INST-001';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'ACR-001';
update public.pop_items set total_quantity = 10, warehouse_quantity = 10, assigned_quantity = 0 where internal_code = 'HAB-001';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'RT-000';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'RT-001';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'RT-002';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'RT-003';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'RT-004';
update public.pop_items set total_quantity = 111, warehouse_quantity = 10, assigned_quantity = 101 where internal_code = 'RT-005';

-- Asignaciones reales: qué agencia tiene cada material y en qué estado
insert into public.inventory_assignments (pop_item_id, store_id, zone_id, assigned_quantity, delivery_date, status, notes)
select pi.id, s.id, s.zone_id, 1, date '2025-01-15', v.status::assignment_status, v.notes
from (values
  ('LET-001', 'E-01', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-01', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-01', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-01', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-01', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-01', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-01', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-01', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-01', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-01', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-02', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-02', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-02', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-02', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-02', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-02', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-02', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-02', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-02', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-02', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-03', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-03', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-04', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-04', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-05', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-05', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-05', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-05', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-05', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-05', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-05', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-05', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-05', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-05', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-06', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-06', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-06', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-06', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-06', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-06', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-06', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-06', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-06', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-06', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-08', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-08', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-08', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-08', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-08', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-08', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-08', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-08', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-08', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-08', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-09', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-09', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-09', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-09', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-10', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-10', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-10', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-10', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-100', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-100', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-100', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-100', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-100', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-100', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-100', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-100', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-100', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-100', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-101', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-101', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-101', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-102', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-102', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-102', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-102', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-102', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-102', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-102', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-102', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-102', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-102', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-104', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-104', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-104', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-104', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-104', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-104', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-104', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-104', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-104', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-104', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-106', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-106', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-106', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-106', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-106', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-106', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-106', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-106', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-106', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-106', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-107', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-107', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-107', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-108', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-108', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-108', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-109', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-109', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-11', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-11', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-11', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-110', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-110', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-110', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-110', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-110', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-110', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-110', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-110', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-110', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-110', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-111', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-111', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-111', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-111', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-111', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-111', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-111', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-111', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-111', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-111', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-112', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-112', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-112', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-112', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-112', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-112', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-112', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-112', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-112', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-112', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-113', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-113', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-113', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-113', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-114', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-114', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-114', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-114', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-114', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-114', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-114', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-114', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-114', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-114', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-115', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-115', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-115', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-115', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-115', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-115', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-115', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-115', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-115', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-115', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-116', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-116', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-116', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-116', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-116', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-116', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-116', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-116', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-116', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-116', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-117', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-117', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-117', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-117', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-117', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-117', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-117', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-117', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-117', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-117', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-119', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-119', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-119', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-119', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-119', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-119', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-119', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-119', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-119', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-119', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-12', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-12', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-12', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-12', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-12', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-12', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-12', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-12', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-12', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-12', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-120', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-120', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-120', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-120', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-121', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-121', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-121', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-121', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-121', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-121', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-121', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-121', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-121', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-121', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-13', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-13', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-13', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-13', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-13', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-13', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-13', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-13', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-13', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-13', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-14', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-14', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-14', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-14', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-14', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-14', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-14', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-14', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-14', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-14', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-15', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-15', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-15', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-15', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-15', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-15', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-15', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-15', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-15', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-15', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-159', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-159', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-159', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-159', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-159', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-159', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-159', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-159', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-159', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-159', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-16', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-160', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-160', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-160', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-160', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-160', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-160', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-160', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-160', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-160', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-160', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-161', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-161', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-161', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-162', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-162', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-166', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-166', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-168', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-168', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-168', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-168', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-168', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-168', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-168', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-168', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-168', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-168', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-171', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-171', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-171', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-171', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-171', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-171', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-171', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-171', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-171', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-171', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-172', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-172', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-172', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-18', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-18', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-18', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-18', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-18', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-18', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-18', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-18', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-18', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-18', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-19', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-19', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-19', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-19', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-200', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-200', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-201', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-201', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-201', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-202', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-202', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-202', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-202', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-203', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-203', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-203', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-204', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-204', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-204', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-204', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-205', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-205', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-205', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-205', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-206', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-206', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-206', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-206', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-206', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-206', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-206', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-206', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-206', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-206', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-207', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-207', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-207', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-207', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-208', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-208', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-208', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-208', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-208', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-208', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-208', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-208', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-208', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-208', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-209', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-209', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-209', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-209', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-209', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-209', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-209', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-209', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-209', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-209', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-21', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-21', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-21', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-21', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-210', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-210', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-210', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-210', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-210', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-210', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-210', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-210', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-210', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-210', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-211', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-211', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-211', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-211', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-212', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-212', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-212', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-212', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-22', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-22', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-22', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-22', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-22', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-22', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-22', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-22', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-22', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-22', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-23', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-23', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-23', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-23', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-24', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-24', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-24', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-24', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-24', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-24', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-24', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-24', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-24', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-24', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-25', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-25', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-25', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-25', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-25', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-25', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-25', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-25', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-25', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-25', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-26', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-26', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-27', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-27', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-27', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-28', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-28', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-28', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-28', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-28', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-28', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-28', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-28', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-28', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-28', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-29', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-29', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-29', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-29', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-30', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-30', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-30', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-30', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-30', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-30', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-30', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-30', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-30', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-30', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-32', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-32', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-32', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-32', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-32', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-32', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-32', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-32', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-32', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-32', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-33', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-33', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-33', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-33', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('PIN-001', 'E-34', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-34', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-34', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-34', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-35', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-35', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-35', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-35', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-35', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-35', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-35', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-35', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-35', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-35', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-36', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-36', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-36', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-36', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-36', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-36', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-36', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-36', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-36', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-36', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-38', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-38', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-38', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-38', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-38', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-38', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-38', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-38', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-38', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-38', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-39', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-39', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-39', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-44', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-44', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-44', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-44', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-44', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-44', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-44', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-44', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-44', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-44', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-46', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-46', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-46', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-46', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-46', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-46', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-46', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-46', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-46', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-46', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-48', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-48', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-48', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-48', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-49', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-49', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-49', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-49', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-49', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-49', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-49', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-49', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-49', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-49', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-50', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-50', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-50', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-50', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-51', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-51', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-51', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-51', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-52', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-52', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-53', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-53', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-53', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-54', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-54', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-54', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-54', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-54', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-54', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-002', 'E-54', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-003', 'E-54', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-004', 'E-54', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-005', 'E-54', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('LET-001', 'E-55', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-55', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-55', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-55', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-55', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-55', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-55', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-55', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-55', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-55', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-56', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-56', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-56', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-56', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-56', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-56', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-56', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-56', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-56', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-56', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-57', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-57', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-57', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-57', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-57', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-57', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-57', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-57', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-57', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-57', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-58', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-58', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-58', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-58', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-58', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-58', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-58', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-58', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-58', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-58', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-59', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-59', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-59', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-59', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-59', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-59', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-59', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-59', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-59', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-59', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-60', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-60', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-60', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-60', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-60', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-60', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-60', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-60', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-60', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-60', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-61', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-61', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-61', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-61', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-62', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-62', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-62', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-62', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-63', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-63', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-63', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-63', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-64', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-64', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-64', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-64', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-64', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-64', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-64', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-64', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-64', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-64', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-65', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-65', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('INST-001', 'E-65', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-65', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-65', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-65', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-65', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-65', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-65', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-65', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-66', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-66', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-66', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-66', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-67', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('INST-001', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-67', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('RT-001', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-67', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-68', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-000', 'E-68', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-68', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-69', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-69', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-69', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-001', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-69', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('PIN-001', 'E-70', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-70', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-000', 'E-70', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-002', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-003', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-004', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('RT-005', 'E-70', 'maintenance', 'Distribución inicial - Desgastado, requiere seguimiento'),
  ('LET-001', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-71', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-71', 'good', 'Distribución inicial - Buen estado'),
  ('LET-001', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('PIN-001', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('INST-001', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('ACR-001', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('RT-000', 'E-72', 'damaged', 'Distribución inicial - Dañado, requiere reparación o reemplazo'),
  ('RT-001', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('RT-002', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('RT-003', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('RT-004', 'E-72', 'good', 'Distribución inicial - Buen estado'),
  ('RT-005', 'E-72', 'good', 'Distribución inicial - Buen estado')
) as v(item_code, store_code, status, notes)
join public.pop_items pi on pi.internal_code = v.item_code
join public.stores s on s.code = v.store_code;

-- Bitácora derivada: registra la distribución inicial como movimiento de tipo 'delivery'
insert into public.inventory_movements (pop_item_id, store_id, assignment_id, movement_type, quantity, notes, created_at)
select ia.pop_item_id, ia.store_id, ia.id, 'delivery', ia.assigned_quantity, ia.notes, now()
from public.inventory_assignments ia
where ia.notes like 'Distribución inicial%';
